name: deploy_selfhosted

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  build-and-deploy:
    runs-on: arhitectvirt

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install .NET dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore

    - name: Publish
      run: dotnet publish --configuration Debug --output publish_output

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x' # Ensures Node.js >= 20.0.0
        cache: 'npm'

    - name: Ensure npm version >= 10.0.0
      run: npm install -g npm@^10.0.0

    - name: Install npm dependencies
      run: npm install

    - name: Deploy to folder
      run: |
        if (-Not (Test-Path -Path "C:\continous_delivery\waste_sniffer")) {
          New-Item -ItemType Directory -Force -Path "C:\continous_delivery\waste_sniffer"
        }
        Copy-Item -Path "publish_output\*" -Destination "C:\continous_delivery\waste_sniffer" -Recurse -Force

    - name: Notify success
      if: success()
      run: |
        echo "Deployment to C:\continous_delivery\waste_sniffer was successful!"

    - name: Notify failure
      if: failure()
      run: |
        echo "Deployment to C:\continous_delivery\waste_sniffer failed."
