# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET-Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # This event allows manual triggering

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [windows-2019]
        #does not build on ubuntu-latest
        os: [windows-2019, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Clean
      run: dotnet clean --configuration Release

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Display OS version
      run: echo "Running on ${{ matrix.os }}"
