name: test_gh_runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # This event allows manual triggering

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] # Uncomment to enable testing across all platforms
      fail-fast: false                                                        

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run Tests
      run: dotnet test --settings ExcludeCodeCoverage.runsettings.xml --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test-results.trx"

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: Tests/TestResults/*/coverage.cobertura.xml

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Generate HTML report
      run: reportgenerator "-reports:Tests/TestResults/*/coverage.cobertura.xml" "-targetdir:./coverage-report" "-reporttypes:Html"

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html-report
        path: ./coverage-report

    - name: Upload TRX report
      uses: actions/upload-artifact@v3
      with:
        name: trx-report
        path: Tests/TestResults/**/*.trx

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Unit Tests'
        path: Tests/TestResults/**/*.trx
        reporter: dotnet-trx
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
