name: .NET-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # This event allows manual triggering

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] # Uncomment to enable testing across all platforms
      fail-fast: false                                                        

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run Tests
      run: dotnet test --settings ExcludeCodeCoverage.runsettings.xml --collect:"XPlat Code Coverage" --verbosity normal --logger "trx;LogFileName=test-results.trx"

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: Tests/TestResults/*/coverage.cobertura.xml

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Generate HTML report
      run: reportgenerator "-reports:Tests/TestResults/*/coverage.cobertura.xml" "-targetdir:./coverage-report" "-reporttypes:Html"

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html-report
        path: ./coverage-report

    - name: Install trx2junit
      run: dotnet tool install -g trx2junit --tool-path ./dotnet-global-tools

    - name: Convert TRX to JUnit
      run: |
        mkdir junit-results
        ./dotnet-global-tools/trx2junit ./Tests/TestResults/**/*.trx --output junit-results

    - name: Upload JUnit Test Results
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-results
        path: junit-results/*.xml

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Unit Tests'
        path: junit-results/*.xml
        reporter: 'junit'
