name: integration_test_gh

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # This event allows manual triggering

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: waste_detection_test_integration
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run Integration Tests
      run: dotnet test --filter "Category=Integration" --logger "trx;LogFileName=integration-test-results.trx"
      env:
        TestConnectionString: "Host=localhost;Port=5434;Database=waste_detection_test_integration;Username=postgres;Password=admin;Pooling=true;"

    - name: Upload TRX report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: integration-test-results
        path: "**/integration-test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Integration Tests'
        path: "**/integration-test-results.trx"
        reporter: dotnet-trx
