name: integration_test_gh

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # This event allows manual triggering

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup PostgreSQL with PostGIS
      run: |
        docker pull postgis/postgis:16-3.4
        docker run -d --name postgres -e POSTGRES_DB=waste_detection_test_v3 -e POSTGRES_PASSWORD=admin -e POSTGRES_USER=postgres -p 5434:5432 postgis/postgis:16-3.4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run Integration Tests
      run: dotnet test --filter "Category=Integration" --logger "trx;LogFileName=integration-test-results.trx"
      env:
        TestConnectionString: "Host=localhost;Port=5434;Database=waste_detection_test_v3;Username=postgres;Password=admin;Pooling=true;"

    - name: Upload TRX report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: integration-test-results
        path: "**/integration-test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Integration Tests'
        path: "**/integration-test-results.trx"
        reporter: dotnet-trx
